"""Initial schema: datasets, merchants, events, obligations, edges, runs, results

Revision ID: eea85a7d24ef
Revises: 
Create Date: 2026-08-28 02:17:49.427484
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version')
    )
    op.create_table('dependency_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('estimator', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('is_ground_truth', sa.Boolean(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('pass_through', sa.Float(), nullable=False),
    sa.Column('conditional_probability', sa.Float(), nullable=False),
    sa.Column('excitation_alpha', sa.Float(), nullable=False),
    sa.Column('excitation_decay', sa.Float(), nullable=False),
    sa.Column('base_intensity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lag_mu_log', sa.Float(), nullable=False),
    sa.Column('lag_sigma_log', sa.Float(), nullable=False),
    sa.Column('lag_floor_hours', sa.Float(), nullable=False),
    sa.Column('lag_max_hours', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'source_id', 'target_id', 'estimator', 'model_version', name='uq_dependency_edge')
    )
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.create_index('ix_dependency_source', ['dataset_id', 'source_id'], unique=False)
        batch_op.create_index('ix_dependency_target', ['dataset_id', 'target_id'], unique=False)
        batch_op.create_index('ix_dependency_truth', ['dataset_id', 'is_ground_truth'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('prediction_id', sa.String(length=64), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('shock_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('predictor', sa.String(length=48), nullable=True),
    sa.Column('optimizer', sa.String(length=48), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('horizon_hours', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('hit_time_mae_hours', sa.Float(), nullable=True),
    sa.Column('disruption_prevented', sa.Float(), nullable=True),
    sa.Column('optimality_gap', sa.Float(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_evaluations_predictor', ['predictor', 'model_version'], unique=False)
        batch_op.create_index('ix_evaluations_run', ['run_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    op.create_table('intervention_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('shock_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('optimizer', sa.String(length=64), nullable=True),
    sa.Column('budget_minor', sa.BigInteger(), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=True),
    sa.Column('total_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('baseline_disruption', sa.Float(), nullable=True),
    sa.Column('residual_disruption', sa.Float(), nullable=True),
    sa.Column('interventions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    with op.batch_alter_table('intervention_plans', schema=None) as batch_op:
        batch_op.create_index('ix_plans_shock', ['shock_id'], unique=False)

    op.create_table('liquidity_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('cash_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_drawn_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('operating_floor_minor', sa.BigInteger(), nullable=False),
    sa.Column('pending_payable_minor', sa.BigInteger(), nullable=False),
    sa.Column('pending_receivable_minor', sa.BigInteger(), nullable=False),
    sa.Column('overdue_payable_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidity_states', schema=None) as batch_op:
        batch_op.create_index('ix_liquidity_states_lookup', ['dataset_id', 'merchant_id', 't'], unique=False)

    op.create_table('node_exposures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('expected_shortfall_minor', sa.BigInteger(), nullable=False),
    sa.Column('expected_hit_t', sa.Float(), nullable=True),
    sa.Column('hit_t_lower', sa.Float(), nullable=True),
    sa.Column('hit_t_upper', sa.Float(), nullable=True),
    sa.Column('hop_distance', sa.Integer(), nullable=True),
    sa.Column('contributing_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', 'merchant_id', name='uq_node_exposure')
    )
    with op.batch_alter_table('node_exposures', schema=None) as batch_op:
        batch_op.create_index('ix_node_exposures_prediction', ['prediction_id'], unique=False)

    op.create_table('node_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('systemic_weight', sa.Float(), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('was_shocked', sa.Boolean(), nullable=False),
    sa.Column('became_constrained', sa.Boolean(), nullable=False),
    sa.Column('became_defaulted', sa.Boolean(), nullable=False),
    sa.Column('is_affected', sa.Boolean(), nullable=False),
    sa.Column('first_constrained_t', sa.Float(), nullable=True),
    sa.Column('first_defaulted_t', sa.Float(), nullable=True),
    sa.Column('hop_distance', sa.Integer(), nullable=True),
    sa.Column('value_delayed_minor', sa.BigInteger(), nullable=False),
    sa.Column('weighted_delay', sa.Float(), nullable=False),
    sa.Column('defaults_caused', sa.Integer(), nullable=False),
    sa.Column('deficit_integral', sa.Float(), nullable=False),
    sa.Column('min_buffer_minor', sa.BigInteger(), nullable=False),
    sa.Column('final_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('obligations_missed', sa.Integer(), nullable=False),
    sa.Column('obligations_settled_late', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'merchant_id', name='uq_node_outcome')
    )
    with op.batch_alter_table('node_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_node_outcomes_run', ['run_id'], unique=False)

    op.create_table('obligations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('debtor_id', sa.String(length=64), nullable=False),
    sa.Column('creditor_id', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_minor', sa.BigInteger(), nullable=False),
    sa.Column('issued_t', sa.Float(), nullable=False),
    sa.Column('due_t', sa.Float(), nullable=False),
    sa.Column('original_due_t', sa.Float(), nullable=True),
    sa.Column('settled_t', sa.Float(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('parent_obligation_id', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'obligation_id', name='uq_obligation')
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index('ix_obligations_creditor', ['dataset_id', 'creditor_id', 'due_t'], unique=False)
        batch_op.create_index('ix_obligations_debtor', ['dataset_id', 'debtor_id', 'due_t'], unique=False)
        batch_op.create_index('ix_obligations_status', ['dataset_id', 'status'], unique=False)

    op.create_table('payment_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('payer_id', sa.String(length=64), nullable=False),
    sa.Column('payee_id', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('obligation_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settlement_lag_hours', sa.Float(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'event_id', name='uq_payment_event')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index('ix_payment_events_external', ['external_id'], unique=False)
        batch_op.create_index('ix_payment_events_pair', ['dataset_id', 'payer_id', 'payee_id', 't'], unique=False)
        batch_op.create_index('ix_payment_events_payee', ['dataset_id', 'payee_id', 't'], unique=False)
        batch_op.create_index('ix_payment_events_payer', ['dataset_id', 'payer_id', 't'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('shock_id', sa.String(length=64), nullable=True),
    sa.Column('predictor', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('horizon_hours', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('inference_ms', sa.Float(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_predictions_shock', ['shock_id', 'predictor'], unique=False)

    op.create_table('propagation_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('counterparty_id', sa.String(length=64), nullable=True),
    sa.Column('obligation_id', sa.String(length=64), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('caused_by', sa.String(length=64), nullable=True),
    sa.Column('hop', sa.Integer(), nullable=False),
    sa.Column('balance_after_minor', sa.BigInteger(), nullable=True),
    sa.Column('buffer_after_minor', sa.BigInteger(), nullable=True),
    sa.Column('status_after', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.create_index('ix_propagation_merchant', ['run_id', 'merchant_id', 't'], unique=False)
        batch_op.create_index('ix_propagation_run', ['run_id', 'sequence'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('parent_run_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('shock_id', sa.String(length=64), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seeds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('code_version', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_dataset', ['dataset_version'], unique=False)
        batch_op.create_index('ix_runs_experiment', ['experiment_id'], unique=False)
        batch_op.create_index('ix_runs_kind_status', ['kind', 'status'], unique=False)

    op.create_table('shocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shock_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_magnitude_minor', sa.BigInteger(), nullable=False),
    sa.Column('onset_t', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shock_id')
    )
    with op.batch_alter_table('shocks', schema=None) as batch_op:
        batch_op.create_index('ix_shocks_dataset', ['dataset_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_event')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index('ix_webhook_processed', ['processed', 'received_at'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('opening_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('operating_floor_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('exogenous_inflow_rate', sa.Float(), nullable=False),
    sa.Column('operating_burn_rate', sa.Float(), nullable=False),
    sa.Column('payment_discipline', sa.Float(), nullable=False),
    sa.Column('stress_threshold_ratio', sa.Float(), nullable=False),
    sa.Column('systemic_weight', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'merchant_id', name='uq_merchant_per_dataset')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index('ix_merchants_dataset', ['dataset_id'], unique=False)
        batch_op.create_index('ix_merchants_external', ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index('ix_merchants_external')
        batch_op.drop_index('ix_merchants_dataset')

    op.drop_table('merchants')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_processed')

    op.drop_table('webhook_events')
    with op.batch_alter_table('shocks', schema=None) as batch_op:
        batch_op.drop_index('ix_shocks_dataset')

    op.drop_table('shocks')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_kind_status')
        batch_op.drop_index('ix_runs_experiment')
        batch_op.drop_index('ix_runs_dataset')

    op.drop_table('runs')
    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.drop_index('ix_propagation_run')
        batch_op.drop_index('ix_propagation_merchant')

    op.drop_table('propagation_events')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_shock')

    op.drop_table('predictions')
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_events_payer')
        batch_op.drop_index('ix_payment_events_payee')
        batch_op.drop_index('ix_payment_events_pair')
        batch_op.drop_index('ix_payment_events_external')

    op.drop_table('payment_events')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index('ix_obligations_status')
        batch_op.drop_index('ix_obligations_debtor')
        batch_op.drop_index('ix_obligations_creditor')

    op.drop_table('obligations')
    with op.batch_alter_table('node_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_node_outcomes_run')

    op.drop_table('node_outcomes')
    with op.batch_alter_table('node_exposures', schema=None) as batch_op:
        batch_op.drop_index('ix_node_exposures_prediction')

    op.drop_table('node_exposures')
    with op.batch_alter_table('liquidity_states', schema=None) as batch_op:
        batch_op.drop_index('ix_liquidity_states_lookup')

    op.drop_table('liquidity_states')
    with op.batch_alter_table('intervention_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_plans_shock')

    op.drop_table('intervention_plans')
    op.drop_table('experiments')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluations_run')
        batch_op.drop_index('ix_evaluations_predictor')

    op.drop_table('evaluations')
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_dependency_truth')
        batch_op.drop_index('ix_dependency_target')
        batch_op.drop_index('ix_dependency_source')

    op.drop_table('dependency_edges')
    op.drop_table('datasets')
    # ### end Alembic commands ###
