"""provenance and import runs

Revision ID: 21219792f7f7
Revises: 0001_initial
Create Date: 2026-08-29 00:27:09.032295
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_provenance"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_provenance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('source_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=128), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('raw_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('raw_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('raw_currency', sa.String(length=8), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_id', name='uq_provenance_source')
    )
    with op.batch_alter_table('event_provenance', schema=None) as batch_op:
        batch_op.create_index('ix_provenance_dataset', ['dataset_id'], unique=False)
        batch_op.create_index('ix_provenance_event', ['event_id'], unique=False)
        batch_op.create_index('ix_provenance_ingested', ['ingested_at'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('window_from', sa.BigInteger(), nullable=True),
    sa.Column('window_to', sa.BigInteger(), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index('ix_import_runs_source', ['source_system', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_import_runs_source')

    op.drop_table('import_runs')
    with op.batch_alter_table('event_provenance', schema=None) as batch_op:
        batch_op.drop_index('ix_provenance_ingested')
        batch_op.drop_index('ix_provenance_event')
        batch_op.drop_index('ix_provenance_dataset')

    op.drop_table('event_provenance')
    # ### end Alembic commands ###
